// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroCompleto2.BAL;

namespace RegistroCompleto2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("RegistroCompleto2.Entidades.Roles", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("RolID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            Descripcion = "Aministrador"
                        },
                        new
                        {
                            RolID = 2,
                            Descripcion = "Supervisor"
                        });
                });

            modelBuilder.Entity("RegistroCompleto2.Entidades.Usuarios", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RolID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("alias")
                        .HasColumnType("TEXT");

                    b.Property<bool>("avtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaingreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioID");

                    b.HasIndex("RolID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RegistroCompleto2.Entidades.Usuarios", b =>
                {
                    b.HasOne("RegistroCompleto2.Entidades.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolID");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
